export const constants = {
    LOAD_ITEMS_REQUEST: 'LOAD_ITEMS_REQUEST',
    LOAD_ITEMS_FAILURE: 'LOAD_ITEMS_FAILURE',
    LOAD_ITEMS_SUCCESS: 'LOAD_ITEMS_SUCCESS',
    SET_SELECTED_BRANDS: 'SET_SELECTED_BRANDS',
    SET_SELECTED_WEIGHTS: 'SET_SELECTED_WEIGHTS',
    CLEAR_SELECTED_FILTERS: 'REMOVE_ITEM_FROM_CART',
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    REMOVE_ITEM_FROM_CART: 'REMOVE_ITEM_FROM_CART',
    DECREASE_ITEM_CART: 'DECREASE_ITEM_CART',
    INCREASE_ITEM_CART: 'INCREASE_ITEM_CART',
    CLEAR_CART: 'CLEAR_CART'
}