export const constants = {
    LOAD_ITEMS_REQUEST: 'LOAD_ITEMS_REQUEST',
    LOAD_ITEMS_FAILURE: 'LOAD_ITEMS_FAILURE',
    LOAD_ITEMS_SUCCESS: 'LOAD_ITEMS_SUCCESS',
    SET_SELECTED_BRANDS: 'SET_SELECTED_BRANDS',
    SET_SELECTED_WEIGHTS: 'SET_SELECTED_WEIGHTS'
}